spring:
  datasource:
    url: jdbc:mysql://kimjeju-database-server.csmds0ouj1iw.ap-northeast-2.rds.amazonaws.com/Todo_database?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: overrain12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true # sql 보기 좋게 변경
